name: Maven Package

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        
    - name: Install dependencies
      run: mvn install

    - name: Build with Maven
      run: mvn assembly:single

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ format('Release {0}', github.sha[0:8]) }}
        body: |
          Release

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/firebyte.jar

    - name: Deploy
      uses: actions/deploy-releases@v1
      with:
        api-key: ${{ secrets.GITHUB_TOKEN }}
        file: target/firebyte.jar
        release: ${{ steps.create_release.outputs.id }}
