name: Maven Package

on: 
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Install dependencies
      run: mvn install

    - name: Build with Maven
      run: mvn assembly:single

    - name: Move JAR to Root
      run: mv target/login-java-netminder-1.1.jar firebyte.jar
